//
// SPDX-License-Identifier: GPL-3.0
//
// This file is part of the NWScript compiler open source release.
//
// The initial source release is licensed under GPL-3.0.
//
// All subsequent changes you submit are required to be licensed under MIT.
//
// However, the project overall will still be GPL-3.0.
//
// The intent is for the base game to be able to pick up changes you explicitly
// submit for inclusion painlessly, while ensuring the overall project source code
// remains available for everyone.
//

///////////////////////////////////////////////////////////////////////////////
//                 BIOWARE CORP. CONFIDENTIAL INFORMATION.                   //
//               COPYRIGHT BIOWARE CORP. ALL RIGHTS RESERVED                 //
///////////////////////////////////////////////////////////////////////////////

//::///////////////////////////////////////////////////////////////////////////
//::
//::  Script Project
//::
//::  Copyright (c) 2002, BioWare Corp.
//::
//::///////////////////////////////////////////////////////////////////////////
//::
//::  ScriptErrors.h
//::
//::  A project-specific header file, specifying error constants that relate
//::  to string references in the game code.
//::
//::///////////////////////////////////////////////////////////////////////////
//::
//::  Created By: Mark Brockington
//::  Created On: Oct. 24, 2002
//::
//::///////////////////////////////////////////////////////////////////////////

// All error codes in the following file relate to negative values of string references.

#ifndef __SCRIPTERRORS_H__
#define __SCRIPTERRORS_H__

#define STRREF_CSCRIPTCOMPILER_ERROR_UNEXPECTED_CHARACTER   -560
#define STRREF_CSCRIPTCOMPILER_ERROR_FATAL_COMPILER_ERROR  -561
#define STRREF_CSCRIPTCOMPILER_ERROR_PROGRAM_COMPOUND_STATEMENT_AT_START  -562
#define STRREF_CSCRIPTCOMPILER_ERROR_UNEXPECTED_END_COMPOUND_STATEMENT  -563
#define STRREF_CSCRIPTCOMPILER_ERROR_AFTER_COMPOUND_STATEMENT_AT_END  -564
#define STRREF_CSCRIPTCOMPILER_ERROR_PARSING_VARIABLE_LIST  -565
#define STRREF_CSCRIPTCOMPILER_ERROR_UNKNOWN_STATE_IN_COMPILER  -566
#define STRREF_CSCRIPTCOMPILER_ERROR_INVALID_DECLARATION_TYPE  -567
#define STRREF_CSCRIPTCOMPILER_ERROR_NO_LEFT_BRACKET_ON_EXPRESSION  -568
#define STRREF_CSCRIPTCOMPILER_ERROR_NO_RIGHT_BRACKET_ON_EXPRESSION  -569
#define STRREF_CSCRIPTCOMPILER_ERROR_BAD_START_OF_STATEMENT  -570
#define STRREF_CSCRIPTCOMPILER_ERROR_NO_LEFT_BRACKET_ON_ARG_LIST  -571
#define STRREF_CSCRIPTCOMPILER_ERROR_NO_RIGHT_BRACKET_ON_ARG_LIST  -572
#define STRREF_CSCRIPTCOMPILER_ERROR_NO_SEMICOLON_AFTER_EXPRESSION  -573
#define STRREF_CSCRIPTCOMPILER_ERROR_PARSING_ASSIGNMENT_STATEMENT  -574
#define STRREF_CSCRIPTCOMPILER_ERROR_BAD_LVALUE  -575
#define STRREF_CSCRIPTCOMPILER_ERROR_BAD_CONSTANT_TYPE  -576
#define STRREF_CSCRIPTCOMPILER_ERROR_IDENTIFIER_LIST_FULL  -577
#define STRREF_CSCRIPTCOMPILER_ERROR_NON_INTEGER_ID_FOR_INTEGER_CONSTANT  -578
#define STRREF_CSCRIPTCOMPILER_ERROR_NON_FLOAT_ID_FOR_FLOAT_CONSTANT  -579
#define STRREF_CSCRIPTCOMPILER_ERROR_NON_STRING_ID_FOR_STRING_CONSTANT  -580
#define STRREF_CSCRIPTCOMPILER_ERROR_VARIABLE_ALREADY_USED_WITHIN_SCOPE  -581
#define STRREF_CSCRIPTCOMPILER_ERROR_VARIABLE_DEFINED_WITHOUT_TYPE  -582
#define STRREF_CSCRIPTCOMPILER_ERROR_INCORRECT_VARIABLE_STATE_LEFT_ON_STACK  -583
#define STRREF_CSCRIPTCOMPILER_ERROR_NON_INTEGER_EXPRESSION_WHERE_INTEGER_REQUIRED  -584
#define STRREF_CSCRIPTCOMPILER_ERROR_VOID_EXPRESSION_WHERE_NON_VOID_REQUIRED  -585
#define STRREF_CSCRIPTCOMPILER_ERROR_INVALID_PARAMETERS_FOR_ASSIGNMENT  -586
#define STRREF_CSCRIPTCOMPILER_ERROR_DECLARATION_DOES_NOT_MATCH_PARAMETERS  -587
#define STRREF_CSCRIPTCOMPILER_ERROR_LOGICAL_OPERATION_HAS_INVALID_OPERANDS  -588
#define STRREF_CSCRIPTCOMPILER_ERROR_EQUALITY_TEST_HAS_INVALID_OPERANDS  -589
#define STRREF_CSCRIPTCOMPILER_ERROR_COMPARISON_TEST_HAS_INVALID_OPERANDS  -590
#define STRREF_CSCRIPTCOMPILER_ERROR_SHIFT_OPERATION_HAS_INVALID_OPERANDS  -591
#define STRREF_CSCRIPTCOMPILER_ERROR_ARITHMETIC_OPERATION_HAS_INVALID_OPERANDS  -592
#define STRREF_CSCRIPTCOMPILER_ERROR_UNKNOWN_OPERATION_IN_SEMANTIC_CHECK  -593
#define STRREF_CSCRIPTCOMPILER_ERROR_SCRIPT_TOO_LARGE  -594
#define STRREF_CSCRIPTCOMPILER_ERROR_RETURN_STATEMENT_HAS_NO_PARAMETERS  -595
#define STRREF_CSCRIPTCOMPILER_ERROR_NO_WHILE_AFTER_DO_KEYWORD  -596
#define STRREF_CSCRIPTCOMPILER_ERROR_FUNCTION_DEFINITION_MISSING_NAME  -597
#define STRREF_CSCRIPTCOMPILER_ERROR_FUNCTION_DEFINITION_MISSING_PARAMETER_LIST  -598
#define STRREF_CSCRIPTCOMPILER_ERROR_MALFORMED_PARAMETER_LIST  -599
#define STRREF_CSCRIPTCOMPILER_ERROR_BAD_TYPE_SPECIFIER  -600
#define STRREF_CSCRIPTCOMPILER_ERROR_NO_SEMICOLON_AFTER_STRUCTURE  -601
#define STRREF_CSCRIPTCOMPILER_ERROR_ELLIPSIS_IN_IDENTIFIER  -602
#define STRREF_CSCRIPTCOMPILER_ERROR_FILE_NOT_FOUND  -603
#define STRREF_CSCRIPTCOMPILER_ERROR_INCLUDE_RECURSIVE  -604
#define STRREF_CSCRIPTCOMPILER_ERROR_INCLUDE_TOO_MANY_LEVELS  -605
#define STRREF_CSCRIPTCOMPILER_ERROR_PARSING_RETURN_STATEMENT  -606
#define STRREF_CSCRIPTCOMPILER_ERROR_PARSING_IDENTIFIER_LIST  -607
#define STRREF_CSCRIPTCOMPILER_ERROR_PARSING_FUNCTION_DECLARATION  -608
#define STRREF_CSCRIPTCOMPILER_ERROR_DUPLICATE_FUNCTION_IMPLEMENTATION  -609
#define STRREF_CSCRIPTCOMPILER_ERROR_TOKEN_TOO_LONG  -610
#define STRREF_CSCRIPTCOMPILER_ERROR_UNDEFINED_STRUCTURE -611
#define STRREF_CSCRIPTCOMPILER_ERROR_LEFT_OF_STRUCTURE_PART_NOT_STRUCTURE  - 612
#define STRREF_CSCRIPTCOMPILER_ERROR_RIGHT_OF_STRUCTURE_PART_NOT_FIELD_IN_STRUCTURE  -613
#define STRREF_CSCRIPTCOMPILER_ERROR_UNDEFINED_FIELD_IN_STRUCTURE  -614
#define STRREF_CSCRIPTCOMPILER_ERROR_STRUCTURE_REDEFINED  -615
#define STRREF_CSCRIPTCOMPILER_ERROR_VARIABLE_USED_TWICE_IN_SAME_STRUCTURE  -616
#define STRREF_CSCRIPTCOMPILER_ERROR_FUNCTION_IMPLEMENTATION_AND_DEFINITION_DIFFER  -617
#define STRREF_CSCRIPTCOMPILER_ERROR_MISMATCHED_TYPES  -618
#define STRREF_CSCRIPTCOMPILER_ERROR_INTEGER_NOT_AT_TOP_OF_STACK  -619
#define STRREF_CSCRIPTCOMPILER_ERROR_RETURN_TYPE_AND_FUNCTION_TYPE_MISMATCHED  -620
#define STRREF_CSCRIPTCOMPILER_ERROR_NOT_ALL_CONTROL_PATHS_RETURN_A_VALUE  -621
#define STRREF_CSCRIPTCOMPILER_ERROR_UNDEFINED_IDENTIFIER  -622
#define STRREF_CSCRIPTCOMPILER_ERROR_NO_FUNCTION_MAIN_IN_SCRIPT  -623
#define STRREF_CSCRIPTCOMPILER_ERROR_FUNCTION_MAIN_MUST_HAVE_VOID_RETURN_VALUE  -624
#define STRREF_CSCRIPTCOMPILER_ERROR_FUNCTION_MAIN_MUST_HAVE_NO_PARAMETERS  -625
#define STRREF_CSCRIPTCOMPILER_ERROR_NON_VOID_FUNCTION_CANNOT_BE_A_STATEMENT  -626
#define STRREF_CSCRIPTCOMPILER_ERROR_BAD_VARIABLE_NAME  -627
#define STRREF_CSCRIPTCOMPILER_ERROR_NON_OPTIONAL_PARAMETER_CANNOT_FOLLOW_OPTIONAL_PARAMETER -628
#define STRREF_CSCRIPTCOMPILER_ERROR_TYPE_DOES_NOT_HAVE_AN_OPTIONAL_PARAMETER -629
#define STRREF_CSCRIPTCOMPILER_ERROR_NON_CONSTANT_IN_FUNCTION_DECLARATION -630
#define STRREF_CSCRIPTCOMPILER_ERROR_PARSING_CONSTANT_VECTOR  -631
#define STRREF_CSCRIPTCOMPILER_ERROR_OPERAND_MUST_BE_AN_INTEGER_LVALUE -1594
#define STRREF_CSCRIPTCOMPILER_ERROR_CONDITIONAL_REQUIRES_SECOND_EXPRESSION -1595
#define STRREF_CSCRIPTCOMPILER_ERROR_CONDITIONAL_MUST_HAVE_MATCHING_RETURN_TYPES -1596
#define STRREF_CSCRIPTCOMPILER_ERROR_MULTIPLE_DEFAULT_STATEMENTS_WITHIN_SWITCH -1597
#define STRREF_CSCRIPTCOMPILER_ERROR_MULTIPLE_CASE_CONSTANT_STATEMENTS_WITHIN_SWITCH -1598
#define STRREF_CSCRIPTCOMPILER_ERROR_CASE_PARAMETER_NOT_A_CONSTANT_INTEGER -1599
#define STRREF_CSCRIPTCOMPILER_ERROR_SWITCH_MUST_EVALUATE_TO_AN_INTEGER -1600
#define STRREF_CSCRIPTCOMPILER_ERROR_NO_COLON_AFTER_DEFAULT_LABEL -1601
#define STRREF_CSCRIPTCOMPILER_ERROR_NO_COLON_AFTER_CASE_LABEL -1602
#define STRREF_CSCRIPTCOMPILER_ERROR_NO_SEMICOLON_AFTER_STATEMENT -1603
#define STRREF_CSCRIPTCOMPILER_ERROR_BREAK_OUTSIDE_OF_LOOP_OR_CASE_STATEMENT -4834
#define STRREF_CSCRIPTCOMPILER_ERROR_TOO_MANY_PARAMETERS_ON_FUNCTION -4835
#define STRREF_CSCRIPTCOMPILER_ERROR_UNABLE_TO_OPEN_FILE_FOR_WRITING -4836
#define STRREF_CSCRIPTCOMPILER_ERROR_UNTERMINATED_STRING_CONSTANT -4855
#define STRREF_CSCRIPTCOMPILER_ERROR_NO_FUNCTION_INTSC_IN_SCRIPT  -5182
#define STRREF_CSCRIPTCOMPILER_ERROR_FUNCTION_INTSC_MUST_HAVE_VOID_RETURN_VALUE  -5183
#define STRREF_CSCRIPTCOMPILER_ERROR_FUNCTION_INTSC_MUST_HAVE_NO_PARAMETERS  -5184
#define STRREF_CSCRIPTCOMPILER_ERROR_JUMPING_OVER_DECLARATION_STATEMENTS_CASE_DISALLOWED -6804
#define STRREF_CSCRIPTCOMPILER_ERROR_JUMPING_OVER_DECLARATION_STATEMENTS_DEFAULT_DISALLOWED -6805
#define STRREF_CSCRIPTCOMPILER_ERROR_ELSE_WITHOUT_CORRESPONDING_IF -6823
#define STRREF_CSCRIPTCOMPILER_ERROR_IF_CONDITION_CANNOT_BE_FOLLOWED_BY_A_NULL_STATEMENT -10407
// New Errors!
#define STRREF_CSCRIPTCOMPILER_ERROR_INVALID_TYPE_FOR_CONST_KEYWORD -3741
#define STRREF_CSCRIPTCOMPILER_ERROR_CONST_KEYWORD_CANNOT_BE_USED_ON_NON_GLOBAL_VARIABLES -3742
#define STRREF_CSCRIPTCOMPILER_ERROR_INVALID_VALUE_ASSIGNED_TO_CONSTANT -3752
#define STRREF_CSCRIPTCOMPILER_ERROR_SWITCH_CONDITION_CANNOT_BE_FOLLOWED_BY_A_NULL_STATEMENT -9081
#define STRREF_CSCRIPTCOMPILER_ERROR_WHILE_CONDITION_CANNOT_BE_FOLLOWED_BY_A_NULL_STATEMENT -9082
#define STRREF_CSCRIPTCOMPILER_ERROR_FOR_STATEMENT_CANNOT_BE_FOLLOWED_BY_A_NULL_STATEMENT -9083
#define STRREF_CSCRIPTCOMPILER_ERROR_CANNOT_INCLUDE_THIS_FILE_TWICE -9155
#define STRREF_CSCRIPTCOMPILER_ERROR_ELSE_CANNOT_BE_FOLLOWED_BY_A_NULL_STATEMENT -40104

#define STRREF_CVIRTUALMACHINE_ERROR_TOO_MANY_INSTRUCTIONS          -632
#define STRREF_CVIRTUALMACHINE_ERROR_TOO_MANY_LEVELS_OF_RECURSION   -633
#define STRREF_CVIRTUALMACHINE_ERROR_FILE_NOT_OPENED                -634
#define STRREF_CVIRTUALMACHINE_ERROR_FILE_NOT_COMPILED_SUCCESSFULLY -635
#define STRREF_CVIRTUALMACHINE_ERROR_INVALID_AUX_CODE               -636
#define STRREF_CVIRTUALMACHINE_ERROR_NULL_VIRTUAL_MACHINE_NODE      -637
#define STRREF_CVIRTUALMACHINE_ERROR_STACK_OVERFLOW                 -638
#define STRREF_CVIRTUALMACHINE_ERROR_STACK_UNDERFLOW                -639
#define STRREF_CVIRTUALMACHINE_ERROR_INVALID_OP_CODE                -640
#define STRREF_CVIRTUALMACHINE_ERROR_INVALID_EXTRA_DATA_ON_OP_CODE  -641
#define STRREF_CVIRTUALMACHINE_ERROR_INVALID_COMMAND                -642
#define STRREF_CVIRTUALMACHINE_ERROR_FAKE_SHORTCUT_LOGICAL_OPERATION  -643
#define STRREF_CVIRTUALMACHINE_ERROR_DIVIDE_BY_ZERO                   -644
#define STRREF_CVIRTUALMACHINE_ERROR_FAKE_ABORT_SCRIPT                -645
#define STRREF_CVIRTUALMACHINE_ERROR_IP_OUT_OF_CODE_SEGMENT           -646
#define STRREF_CVIRTUALMACHINE_ERROR_COMMAND_IMPLEMENTER_NOT_SET      -647
#define STRREF_CVIRTUALMACHINE_ERROR_UNKNOWN_TYPE_ON_RUN_TIME_STACK   -648

// This is not actually a string reference, but a separate error code
// to prevent the same error from being reported inside an include file
// and in the main file that contains the include.  So, you don't have to
// put this one into the string table.
// THIS ERROR CAN NOT MATCH ANY OF THE OTHER ERRORS LISTED IN THIS FILE!
#define STRREF_CSCRIPTCOMPILER_ERROR_ALREADY_PRINTED   -1

#endif // __SCRIPTERRORS_H__
